[package]
name = "d_bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.8"
tokio = { version = "1.8.0", features = ["full"] }
serde_yaml = "0.8.17"
serde = "1.0.126"
rand = "0.8.4"